### PR TITLE
Adding sensitive params

### PR DESCRIPTION
**Pull request by danvela**
This will allow user to mask sensitive values during build

sample bespin.yml file
`...`
`sensitive_params:`
`- Username`
`- Password`
`...`

Output
`[`
`    {`
`        "ParameterValue": "XXXXXXXXXXXX",`
`        "ParameterKey": "Username"`
`    },`
` ... omitted...`
`    {`
`        "ParameterValue": "XXXXXXXXXXXX",`
`        "ParameterKey": "Password"`
`    },`
` ... omitted...`
`]`

### CODE REVIEW

**Comment by delfick** [comment]
cool, I'll accept this, though I'll change `XXXXXXX` to be `<<redacted>>`

**Comment by delfick** [comment]
I've released version 0.7.4 after making this change : https://github.com/delfick/bespin/commit/0e03df8702b24a61f545a63c614af2e52801d2a5

**Comment by danvela** [comment]
awesome.

**Comment by delfick** [comment]
:)

**Pull request merged**
