### PR TITLE
Correctly obtain outputs from template

### PR DESCRIPTION
**Pull request by atward**
Relates #83 

Corrected ability to obtain/resolve values when using yaml templates.

### CODE REVIEW

**Review by delfick — APPROVED** [review]

**Comment by atward** [comment]
Are we retaining support for py2.6?
https://pypi.python.org/pypi/ordereddict

**Comment by delfick** [comment]
personally I don't see much point in supporting python2.6 in Bespin.

**Comment by atward** [comment]
I gave it a shot. That syntax is only valid post ~v20.8 or something of setup
As it's a python file I could do `sys.version_info` and join the install_requires list with a list of additional requires.

**Comment by delfick** [comment]
Easier just to remove python2.6 from the tox.ini and .travis.yml

**Review by delfick — APPROVED** [review]

**Comment by atward** [comment]
Closes #83

**Pull request merged**
