### PR TITLE
Permit variables to reference other variables

### PR DESCRIPTION
**Pull request by atward**
Do multiple passes on params to replace variables. Stop when no futher
changes.

### CODE REVIEW

**Review by delfick — APPROVED** [review]

**Comment by atward** [comment]
@delfick re: build failures. Have you changed anything in travis. This seems unrelated to the PR.

**Comment by delfick** [comment]
hmm, that is indeed odd

**Comment by delfick** [comment]
:( a restart of the tests didn't fix the tests.

I'm not sure what is causing this

**Comment by atward** [comment]
Build failures fixed in #77. rebasing

**Pull request merged**
