### PR TITLE
Travis build test

### PR DESCRIPTION
**Pull request by atward**
Testing travis build against latest working commit (master/HEAD)

### CODE REVIEW

**Comment by atward** [comment]
This should pass based on being code identical to https://travis-ci.org/delfick/bespin/builds/231440325

**Comment by atward** [comment]
Doing diff between good/bad travis builds reveals the obvious:
```
-moto-0.4.31
+moto-1.0.0
```

**Comment by atward** [comment]
https://github.com/spulec/moto/issues/945#issuecomment-301720692

**Review by delfick — APPROVED** [review]

**Comment by atward** [comment]
Closing in favour of #77

**Pull request closed without merging**
